### ISSUE TITLE
Arithmetic Operators

### ISSUE THREAD

**Issue by nsanitate** [apuliasoft/j2se-js#10]
Implement the **arithmetic operators** that allow to overcome the differences between Java and JavaScript.

## Expected Behavior

* Java `a + b` becomes JavaScript `a.add(b)`
* Java `a - b` becomes JavaScript `a.sub(b)`
* Java `a * b` becomes JavaScript `a.mul(b)`
* Java `a / b` becomes JavaScript `a.div(b)`
* Java `a % b` becomes JavaScript `a.mod(b)`

## Acceptance Test
The following program tests the arithmetic operators:
```javascript
const value1 = new Jint(1);
const value2 = new Jint(2);
const value8 = new Jint(8);
const value7 = new Jint(7);

let result = value1.add(value2);
// result is now 3
console.log("1 + 2 = " + result);
let original_result = result;

result = result.sub(value1);
// result is now 2
console.log(original_result + " - 1 = " + result);
original_result = result;

result = result.mul(value2);
// result is now 4
console.log(original_result + " * 2 = " + result);
original_result = result;

result = result.div(value2);
// result is now 2
console.log(original_result + " / 2 = " + result);
original_result = result;

result = result.add(value8);
// result is now 10
console.log(original_result + " + 8 = " + result);
original_result = result;

result = result.mod(value7);
// result is now 3
console.log(original_result + " % 7 = " + result);
```
Output:
```
1 + 2 = 3
3 - 1 = 2
2 * 2 = 4
4 / 2 = 2
2 + 8 = 10
10 % 7 = 3
```
The `+` operator can also be used for concatenating (joining) two strings together, as shown in the following program:
```javascript
var firstString = new Jstring("This is");
var secondString = new Jstring(" a concatenated string.");
var thirdString = firstString.add(secondString);
console.log(thirdString);
```
Output:
```
This is a concatenated string.
```

**Comment by giuseppe-santoro** [comment]
What is the meaning of `rem` in `a.rem(b)`?
Usually `a % b` is also written `a mod b`, see: https://en.wikipedia.org/wiki/Modulo_operation

My proposal is `a.mod(b)`, what do you think @nsanitate?

**Comment by nsanitate** [comment]
In [Java documentation](https://docs.oracle.com/javase/tutorial/java/nutsandbolts/op1.html) `%` represents a remainder operator, so I proposed `rem()`.

IMHO I prefer your solution.
