### ISSUE TITLE
Primitive Data Types

### ISSUE THREAD

**Issue by nsanitate** [apuliasoft/j2se-js#12]
Implement the **primitive data types** that allow to overcome the differences between Java and JavaScript.

## Expected Behavior

* Java `int` becomes JavaScript `Jint`
> The int data type is a 32-bit signed two's complement integer, which has a minimum value of -2<sup>31</sup> and a maximum value of 2<sup>31</sup>-1.

* Java `double` becomes JavaScript `Jdouble`
> The double data type is a double-precision 64-bit IEEE 754 floating point. Its range of values is beyond the scope of this discussion, but is specified in the [Floating-Point Types, Formats, and Values](https://docs.oracle.com/javase/specs/jls/se7/html/jls-4.html#jls-4.2.3) section of the Java Language Specification.

* Java `boolean` becomes JavaScript `Jboolean`
> The boolean data type has only two possible values: true and false. This data type represents one bit of information.

* Java `char` becomes JavaScript `Jchar`
> The char data type is a single 16-bit Unicode character. It has a minimum value of '\u0000' (or 0) and a maximum value of '\uffff' (or 65,535 inclusive).

## Do it later
* Java `byte` becomes JavaScript `Jbyte`
* Java `short` becomes JavaScript `Jshort`
* Java `long` becomes JavaScript `Jlong`
* Java `float` becomes JavaScript `Jfloat`

**Comment by nsanitate** [comment]
Postpone `byte`, `short`, `long` and `float`.

**Comment by giuseppe-santoro** [comment]
in `Postpone` we should add the `unsigned` version of all data types.

**Comment by giuseppe-santoro** [comment]
About long we could use (part of) this implementation: [Closure Library Long](https://google.github.io/closure-library/api/goog.math.Long.html)
