### ISSUE TITLE
Class JObject

### ISSUE THREAD

**Issue by nsanitate** [apuliasoft/j2se-js#14]
Implement class `JObject`, porting of the Java class [`java.lang.Object`](https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html).
> Class Object is the root of the class hierarchy. Every class has Object as a superclass. All objects, including arrays, implement the methods of this class.

## Expected Behavior

* public 0-params constructor `constructor()`
* public method `equals(obj: JObject): Jboolean`
> Indicates whether some other object is "equal to" this one.

* public method `getClass(): JClass<?>`
> Returns the runtime class of this Object.

* public method `hashCode(): Jint`
> Returns a hash code value for the object.

* public method `toString(): JString`
> Returns a string representation of the object.

* protected method `clone(): JObject`
> Creates and returns a copy of this object.

## Do it later
* public method `notify(): void`
* public method `notifyAll(): void`
* public method `wait(): void`
* public method `wait(timeout: Jlong): void`
* public method `wait(timeout: Jlong, nanos: Jint): void`
* protected method `finalize(): void`

**Comment by dammafra** [comment]
I've implemented a method `instanceof(expr: Function)` that emulates the Java operator `instanceof`. However by doing so I'm allowing to appy this "operator" to primitive types too, that isn't possible in Java.

**Comment by nsanitate** [comment]
You could use a stricted type syntax
```typescript
public instanceOf(expr: typeof JObject): Jboolean 
```
