### ISSUE TITLE
Primitive Data Types: Jarray

### ISSUE THREAD

**Issue by nsanitate** [apuliasoft/j2se-js#21]
Implement the **array** type that allow to overcome the differences between Java and JavaScript.

## Expected Behavior

* Declaring a Variable to refer to an Array
* Creating, Initializing, and Accessing an Array
  * shortcut syntax
* Exceptions
  * array index out of bound exception

### Declaring a Variable to refer to an Array
```typescript
let anArray: Jarray<Jdouble>;
```

### Creating, Initializing, and Accessing an Array
```typescript
const anArray = new Jarray<Jdouble>(jint('3'));

anArray.set(jint('0'), jdouble('1.1'));
anArray.set(jint('1'), jdouble('2.2'));
anArray.set(jint('2'), jdouble('3.3'));

console.log("Element at index 0: " + anArray.get(jint('0')));
console.log("Element at index 1: " + anArray.get(jint('1')));
console.log("Element at index 2: " + anArray.get(jint('2')));

// shortcut syntax
const anotherArray = new Jarray<Jdouble>([Jdouble('4.4'), Jdouble('5.5'), Jdouble('6.6')]);

console.log("Element at index 0: " + anotherArray.get(jint('0')));
console.log("Element at index 1: " + anotherArray.get(jint('1')));
console.log("Element at index 2: " + anotherArray.get(jint('2')));
```
Output:
```
Element at index 0: 1.1
Element at index 1: 2.2
Element at index 2: 3.3

Element at index 0: 4.4
Element at index 1: 5.5
Element at index 2: 6.6
```

### Exceptions
```typescript
const anArray = new Jarray<Jdouble>(jint('3'));
console.log("Element at index 3: " + anArray.get(jint('3')));
```
Output:
```
ERROR: JArrayIndexOutOfBoundsException: 3
```

## Do it later

* Multidimensional array (#39)

**Comment by nsanitate** [comment]
Questions:
1. Should we use Jint to set the array cardinality?
2. Should we use Jint to specify an array index?
3. Can we use brackets operator as value accessor?

For question 3, maybe we can use proxies. If not, we can use respectively:
* `array.get(index)` instead of `array[index]`
* `array.set(index, value)` instead of `array[index] = value`

**Comment by nsanitate** [comment]
Answers:

1. Yes, we should use Jint to set array cardinality.
2. Yes, we should use Jint to specify array index.
3. No, the first implementation should use `.get()` and `.set()`.

**Comment by dammafra** [comment]
As specified in the documentation (https://docs.oracle.com/javase/specs/jls/se7/html/jls-10.html), arrays are always objects in Java. Should I implement the JArray class?

**EDIT** Actually the Array Java class documentation says that  "provides static methods to dynamically create and access Java arrays" (https://docs.oracle.com/javase/7/docs/api/java/lang/reflect/Array.html), so I continue to follow the specifications outlined here, implementing Jarray primitive.

**Comment by nsanitate** [comment]
After some experiments I discover:

* `new int[0] instanceof Object` is `true`
* `(new int[]).getClass().getName()` is `[I`
* `(new Integer[]).getClass().getName()` is `[java.lang.Integer`

So I think Array is managed as a native component, but it extends `java.lang.Object`.

**Comment by dammafra** [comment]
In Java, when an array is instantiated by specifying a size n, it is also initialized with n default values of the type chosen., ie `int[] arrayInt = new int[3]; //[0, 0, 0]`. Do I have to replicate the same behaviour?

In order to do this, we should find find a way to get the default value of a generic type T. In Typescript a generic type T can't be used in expressions though. 
(This could be useful: https://stackoverflow.com/questions/29436747/how-can-i-create-a-new-instance-of-the-generic-type-of-my-typescript-class)

**Comment by fdammacco** [comment]
We must find a way to get the default value of a generic type T. In Typescript a generic type T  can't be used in expressions though.

**Comment by nsanitate** [comment]
We should use a different form for every primitive types:
```typescript
let a: Jarray<JInt> = Jintarray(Jint('3'));
```
