### ISSUE TITLE
Primitive Data Types: Jint

### ISSUE THREAD

**Issue by nsanitate** [apuliasoft/j2se-js#23]
Implement the **int** primitive data type that allow to overcome the differences between Java and JavaScript.
> The int data type is a 32-bit signed two's complement integer, which has a minimum value of -2<sup>31</sup> and a maximum value of 2<sup>31</sup>-1.

## Expected Behavior

* Declaring a variable to refer to an int
* Creating, Initializing, and Accessing an int
  * initialize with hexadecimal
  * initialize with binary
* Equality and Relational Operators
  * equal to
  * not equal to
  * greater than
  * greater than or equal to
  * less than
  * less than or equal to
* Arithmetic Operators
  * additive operator
  * subtraction operator
  * multiplication operator
  * division operator
  * remainder operator
* Unary Operators
  * unary plus operator
  * unary minus operator
  * increment operator
  * decrement operator
* Exception
  * incompatible types: possible lossy conversion with long, float o double
  * incompatible types: <type> cannot be converted to int
  
### Declaring a variable to refer to an int
```typescript
let anInt: Jint;
```

### Creating, Initializing, and Accessing an int
```typescript
const anInt = jint('26');
console.log("Int: " + anInt);

// initialize with hexadecimal
const anHex = jint('0x1a');
console.log("Hex: " + anHex);

// initialize with binary
const aBin = jint('0b11010');
console.log("Bin: " + aBin);
```
Output:
```
Int: 26
Hex: 26
Bin: 26
```

### Equality and Relational Operators
```typescript
const value1 = jint('1');
const value2 = jint('2');

if(is(value1.eq(value2)))
   console.log("value1 == value2");

if(is(value1.ne(value2)))
   console.log("value1 != value2");

if(is(value1.gt(value2)))
   console.log("value1 > value2");

if(is(value1.ge(value2)))
   console.log("value1 > value2");

if(is(value1.lt(value2)))
   console.log("value1 < value2");

if(is(value1.le(value2)))
   console.log("value1 <= value2");
```
Output:
```
value1 != value2
value1 <  value2
value1 <= value2
```

### Arithmetic Operators
```typescript
const value8 = jint('8');
const value7 = jint('7');
let result: Jint;

result = value8.add(value7);
console.log("8 + 7 = " + result);

result = value8.sub(value7);
console.log("8 - 7 = " + result);

result = value8.mul(value7);
console.log("8 * 7 = " + result);

result = value8.div(value7);
console.log("8 / 7 = " + result);

result = value8.mod(value7);
console.log("8 % 7 = " + result);
```
Output:
```
8 + 7 = 15
8 - 7 = 1
8 * 7 = 56
8 / 7 = 1
8 % 7 = 1
```

### Unary Operators
```typescript
const value1 = jint('-1');
let result: Jint;

result = value1.plus();
console.log("+(-1) = " + result);

value1.inc();
console.log("++(-1) = " + value1);

value1.dec();
console.log("--(0) = " + value1);

result = value1.minus();
console.log("-(-1) = " + result);
```
Output:
```
+(-1) = -1
++(-1) = 0
--(0) = -1
-(-1) = 1
```

### Exceptions
```typescript
const anInt = jint('10l');
const anotherInt = jint('ten');
```
Output:
```
ERROR: incompatible types: possible lossy conversion from long to int
ERROR: incompatible types: String cannot be converted to int
```

**Comment by dammafra** [comment]
How can I create a factory function named as the class Jint? I've found this that seems useful to me, but I can not apply it to our case.

https://stackoverflow.com/questions/40158295/how-to-define-a-typescript-constructor-and-factory-function-with-the-same-name

**EDIT:** For now, factory function names are lowercased, ie jint.

**Comment by dammafra** [comment]
## Questions
1. In Java, char and int can be used interchangeably, ie in Java is possible to do:
    ``` java
    int anInt = 'c';
    System.out.println(anInt); // prints 99
    ```
    Should we replicate? If so, which of the two alternative below?
    ``` javascript
    // first alternative
    const anInt = jint('c');

    // second alternative
    const anotherInt = jint(jchar('c'));
    ```
     **EDIT:** After reading Jchar specification, I think the second alternative should be the correct one.


2. In Java, primitive types do not automatically set a default value for functions local variables, but only for class members; we set always a default value instead. Should we replicate?
3. Exceptions listed in "Expected Behavior" section are compile time errors in Java and not runtime ones. I still have to handle them?
4. In Java, int can be initialized with an expression, ie in Java is possible to do:
    ``` java
    int anInt = 1 + 2;
    System.out.println(anInt); // prints 3
    ```
    We could easily do this with constructor by number; should we replicate it with constructor by string also? (This could be useful: https://pegjs.org)
5. In Java isn't possible to initialize an int with a double:
    ``` java
    int i = 2.0; // throws compile time error: incompatible types
    ```
    This behaviour is obtained by our constructor by string, but not by constructor by number, ie:
    ``` javascript
    const i = jint(2.0); // OK
    const j = jint ('2.0'); // throws correctly the error
    ```
    Should we resolve this?
 **Note:** In Java, mixed expression initialization like `int anInt = 1 + 2.0;` throws a compile time error `incompatible types: possible lossy conversion from double to int`; in our case, constructor by number works instead.

**Comment by dammafra** [comment]
## Answers:
1. Yes, we should implement the constructor
    ``` javascript
    const anInt: Jint = jint(jchar('c'));
    ```
2. _Not answered yet_
3. _Not answered yet_
4. Such cases are managed in the following way:

    ``` javascript
    const anotherInt: Jint = jint('1').add(jint('2'));
    ```
5. _Not answered yet_

**Comment by nsanitate** [comment]
1. OK.
2. No, let's use default in every case; e.g. when `let i: Jint = jint();` the variable `i` is initialized to value `0` in case it's a class member or a local variable.
3. Yes, we can't raise this type of exceptions at compile time, so we should use JavaScript error at runtime.
4. OK.
5. Let's remove constructor by number.

**Comment by dammafra** [comment]
Implemented mixed operations between `Jint`, `Jdouble` (#24) and `Jchar` (#26). Maybe the code is too duplicated?

**Comment by nsanitate** [comment]
Increment and decrement should change internal values.
