### ISSUE TITLE
Primitive Data Types: Jboolean

### ISSUE THREAD

**Issue by nsanitate** [apuliasoft/j2se-js#25]
Implement the **boolean** primitive data type that allow to overcome the differences between Java and JavaScript.
> The boolean data type has only two possible values: true and false. This data type represents one bit of information.

## Expected Behavior

* Declaring a variable to refer to a boolean
* Creating, Initializing, and Accessing a boolean
* Equality Operators
  * equal to
  * not equal to
* Conditional Operators
  * and
  * or
* Unary Operators
  * logical complement operator
* Exception
  * incompatible types: <type> cannot be converted to boolean
  
### Declaring a variable to refer to a boolean
```typescript
let aBoolean: Jboolean;
```

### Creating, Initializing, and Accessing a boolean
```typescript
const aBoolean = jboolean('true');
console.log("boolean: " + aBoolean);
```
Output:
```
boolean: true
```

### Equality and Conditional Operators
```typescript
const value1 = jboolean('true');
const value2 = jboolean('false');

if(is(value1.eq(value2)))
   console.log("value1 == value2");

if(is(value1.ne(value2)))
   console.log("value1 != value2");

if(is(value1.and(value2)))
   console.log("value1 AND value2");

if(is(value1.or(value2)))
   console.log("value1 OR value2");
```
Output:
```
value1 != value2
value1 OR value2
```

### Unary Operators
```typescript
const value1 = jboolean('true');

result = value1.not();
// result is now false
console.log("!(true) = " + result);
```
Output:
```
!(true) = false
```

### Exceptions
```typescript
const aBoolean = jboolean('not true');
```
Output:
```
ERROR: incompatible types: String cannot be converted to boolean
```

## Do it later
* simulate `short-circuiting` behavior

**Comment by dammafra** [comment]
## Questions

1. In Java, primitive types do not automatically set a default value for functions local variables, but only for class members; we set always a default value instead. Should we replicate?
2. Exceptions listed in "Expected Behavior" section are compile time errors in Java and not runtime ones. I still have to handle them?
3. In Java, boolean can be initialized with an expression, ie in Java is possible to do:
    
    ``` java
    boolean anInt = true && false;
    System.out.println(anInt); // prints false
    ```
    We could easily do this with constructor by boolean; should we replicate it with constructor by string also? (This could be useful: https://pegjs.org)
    **Note:** In Java mixed expression initialization like `boolean aBoolean = true && 0;` throws a compile time error `bad operand types for binary operator '&&'`; in our case, constructor by boolean works instead.

**Comment by nsanitate** [comment]
1. No, let's use default in every case; e.g. when `let b: Jboolean = jboolean();` the variable `b` is initialized to value `false` in case it's a class member or a local variable.
2. Yes, we can't raise this type of exceptions at compile time, so we should use JavaScript error at runtime.
3. Let's implement conditional operators as a function. Wait until I improve the specifications.

**Comment by nsanitate** [comment]
Please, remove constructor by boolean.

**Comment by nsanitate** [comment]
Can we simulate the `short-circuiting` behavior?

**Comment by dammafra** [comment]
Aren't Typescript `&&` and `||` short-circuit? (https://www.tutorialspoint.com/typescript/typescript_logical_operators_examples.htm)

By the way, reading this answer (https://stackoverflow.com/questions/8759868/java-logical-operator-short-circuiting) I think we could do something like:
```typescript
public and(expr: Jboolean) {
    if (this._value === false) {
        return jboolean();
    } else {
       return jboolean((this._value && expr.value).toString());
    }
}

public or(expr: Jboolean) {
    if (this._value === true) {
        return jboolean('true');
    } else {
       return jboolean((this._value && expr.value).toString());
    }
}
```
But if `&&` and `||` in Typescript are themselves short-circuit this type of check seems useless to me.

**Comment by nsanitate** [comment]
I was referring to avoid processing the right side of the operation if this is not a value or a simple variable. For example:
```typescript
function printHelloAndReturnFalse() {
  console.log('Hello!');
  return jboolean(true);
}
const t = jboolean(true);
if(t.or(printHelloAndReturnFalse()) {
  console.log('Check passed!');
}
```
Actual outpult:
```
Hello!
Check passed!
```
Expected output with `short-circuit`:
```
Check passed!
```
A solution could be to pass the function definition, so that if the first check is enough we can avoid to evaluate the right side:
```typescript
function printHelloAndReturnFalse() {
  console.log('Hello!');
  return jboolean(true);
}
const t = jboolean(true);
if(t.or(printHelloAndReturnFalse) {
  console.log('Check passed!');
}
```
But this is not an elegant solution IMHO.

**Comment by dammafra** [comment]
I think it's the only possible way to avoid the evaluation of a function call as parameter of another function, but I agree with you that it's not elegant, especially if the function has input parameters.

**Comment by nsanitate** [comment]
@giuseppe-santoro please, explain why we should use `Jboolean` class instead of the `boolean` primitive type from JavaScript.
