### ISSUE TITLE
Primitive Data Types: Jchar

### ISSUE THREAD

**Issue by nsanitate** [apuliasoft/j2se-js#26]
Implement the **char** primitive data type that allow to overcome the differences between Java and JavaScript.
> The char data type is a single 16-bit Unicode character. It has a minimum value of '\u0000' (or 0) and a maximum value of '\uffff' (or 65,535 inclusive).

## Expected Behavior

* Declaring a variable to refer to a char
* Creating, Initializing, and Accessing a char
  * special escape sequences
  * inizialize with `\u`
  * inizialize with Jint
* Equality and Relational Operators
  * equal to
  * not equal to
  * greater than
  * greater than or equal to
  * less than
  * less than or equal to
* Arithmetic Operators
  * additive operator
  * subtraction operator
  * multiplication operator
  * division operator
  * remainder operator
  * arithmetic with Jint
* Unary Operators
  * unary plus operator
  * unary minus operator
  * increment operator
  * decrement operator
* Exception
  * not a statement
  
### Declaring a variable to refer to a char
```typescript
let aChar: Jchar;
```

### Creating, Initializing, and Accessing a char
```typescript
const aChar = jchar('t');
console.log("Char: " + aChar);

// special escape sequences
const backspace = jchar('\b');
console.log("Backspace: " + backspace);

const tab = jchar('\t');
console.log("Tab: " + tab);

const linefeed = jchar('\n');
console.log("Line Feed: " + linefeed);

const formfeed = jchar('\f');
console.log("Form Feed: " + formfeed);

const carriagereturn = jchar('\r');
console.log("Carriage Return: " + carriagereturn);

const doublequote = jchar('\"');
console.log("Double Quote: " + doublequote);

const singlequote = jchar('\'');
console.log("Single Quote: " + singlequote);

const backslash = jchar('\\');
console.log("Backslash: " + backslash);

// inizialize with integer
const charWithInt = jchar(jint('116'));
console.log("Char with int: " + charWithInt);
```
Output:
```
Char: t
Backspace: 
Tab: 
Line Feed:

Form Feed: 
Carriage Return: 
Double Quote: "
Single Quote: '
Backslash: \
Char with int: t
```

### Equality and Relational Operators
```typescript
const value1 = jchar('f');
const value2 = jchar('t');

if(is(value1.eq(value2)))
   console.log("value1 == value2");

if(is(value1.ne(value2)))
   console.log("value1 != value2");

if(is(value1.gt(value2)))
   console.log("value1 > value2");

if(is(value1.ge(value2)))
   console.log("value1 > value2");

if(is(value1.lt(value2)))
   console.log("value1 < value2");

if(is(value1.le(value2)))
   console.log("value1 <= value2");
```
Output:
```
value1 != value2
value1 <  value2
value1 <= value2
```

### Arithmetic Operators
```typescript
const t = jchar('t');
const f = jchar('f');
let result: Jint;

result = t.add(f);
console.log("t + f = " + result);

result = t.sub(f);
console.log("t - f = " + result);

result = t.mul(f);
console.log("t * f = " + result);

result = t.div(f);
console.log("t / f = " + result);

result = t.mod(f);
console.log("t % f = " + result);

result = t.add(jint(2));
console.log("t + 2 = " + result);
```
Output:
```
t + f = 218
t - f = 14
t * f = 11832
t / f = 1
t % f = 14
t + 2 = 118
```

### Unary Operators
```typescript
const t = jchar('t');
let result: Jint;

result = t.plus();
console.log("+(t) = " + result);

t.inc();
console.log("++(t) = " + t);

t.dec();
console.log("--(t) = " + t);

result = t.minus();
console.log("-(t) = " + result);
```
Output:
```
+(t) = 116
++(t) = u
--(t) = t
-(t) = -116
```

### Exceptions
```typescript
const aChar = jchar('true');
```
Output:
```
ERROR: not a statement
```

**Comment by dammafra** [comment]
## Questions
1. In Java, char and int can be used interchangeably, ie is possible to do mixed assignments and operations:

    ``` java
    int anInt = 'a';
    char aChar = 97;
    System.out.println(anInt == aChar); // prints true
    System.out.println(anInt + aChar); // prints 194
    System.out.println(anInt + 3); // prints 100
    ```
    In our case is possible only to use Jint only for initialize a Jchar or for doing some arithmetic operation on Jchar; vice versa is not possible:
    ``` javascript
    const anInt = jint(jchar('a')); // should be equal to 97
    anInt.add(jchar('a')); // should be equal to 194
    ```
    **Possible solution:** Make Jint and Jchar implement the same interface or extend the same superclass. Maybe doing so will be possible to do something like:
    ``` javascript
    const i: [common interface type] = jchar('a');
    const c: [common interface type] = jint('97');
    ```
2. In order to implement JUnary interface so that methods `plus()` and `minus()` return a Jint, I had to declare `Jchar implements JUnary<Object>`. Like before, make Jint and Jchar implement the same interface or extend the same superclass could be useful, in fact would be more meaningful something like `Jchar implements JUnary<[common interface name]>`, having `plus()` and `minus()` methods return value in accord.
    
    Likewise, In order to implement JArithmetic interface so that all methods return a Jint or have in input a Jint, I had to declare `Jchar implements JArithmetic<Object>`. Like before, make Jint and Jchar implement the same interface or extend the same superclass could be useful, in fact would be more meaningful something like `Jchar implements JArithmetic <[common interface type]>`, having methods return values and input parameters in accord.

**Comment by dammafra** [comment]
## Answers:
1. We can try to make `Jchar extends Jint`; doing that some methods could be implemented in `Jint` only. In case of unsolvable problems try the common interface/abstract class solution.
2. We can make JArithmetic interface have two generics parameters, one for input and one for output (`JArithmetic<P, R>`); doing so, Jchar (or Jint) should implement it like this:

    ``` javascript
    Jchar implements JArithmetic<Jint | Jchar, Jint> {
        ...
    }
    ```

**Comment by nsanitate** [comment]
1. In order to initialize a `char` variable with `int` value we should use the following form:

```typescript
const c: Jchar = jchar(jint('42'));
```

2. Good solution, but could be useful to put generic at method level instead of interface level.

**Comment by dammafra** [comment]
2. I'm having some problems putting generics at method level. For example, having:
``` typescript
// in JUnary.ts
export interface JUnary {
    /** Emulate the operator + */
    plus<T>(): T;

    // ...
}
```
if I do this:
``` typescript
// in jchar_primitive.js
export class Jchar implements JUnary {
    // ...
    public plus(): Jint {
        return jint(+this._value.charCodeAt(0));
    }
    // ...
}
```
I have this error on class declaration: 
`TS2420:Class 'Jchar' incorrectly implements interface 'JUnary'. Types of property 'plus' are incompatible. Type '() => Jint' is not assignable to type '<T>() => T'. Type 'Jint' is not assignable to type 'T'`.

If I do, instead:
``` typescript
// in jchar_primitive.js
export class Jchar implements JUnary {
    // ...
    public plus<Jint>(): Jint {
        return jint(+this._value.charCodeAt(0));
    }
    // ...
}
```
I have the error on method declaration also:
`TS90010:Type 'Jint' is not assignable to type 'Jint'. Two different types with this name exist, but they are unrelated`.

I suspect that if a method is generic in an interface, the class implementing that interface should maintain that method generic too. For now I'm continuing with generics at interface level.

**Comment by dammafra** [comment]
Furthermore, in Java not only arithmetic and unary operators can have mixed operands (ie `int`, `char` or `double`), but also equality and relational operators. I've implemented this behavior by allowing mixed operations between `Jint` (#23), `Jdouble` (#24) and `Jchar`. Maybe the code is too duplicated?
