### ISSUE TITLE
Class JThrowable

### ISSUE THREAD

**Issue by nsanitate** [apuliasoft/j2se-js#29]
Implement class `JThrowable`, porting of the Java class [`java.lang.Throwable`](https://docs.oracle.com/javase/8/docs/api/java/lang/Throwable.html).
> The Throwable class is the superclass of all errors and exceptions in the Java language. Only objects that are instances of this class (or one of its subclasses) are thrown by the Java Virtual Machine or can be thrown by the Java throw statement. Similarly, only this class or one of its subclasses can be the argument type in a catch clause. For the purposes of compile-time checking of exceptions, Throwable and any subclass of Throwable that is not also a subclass of either RuntimeException or Error are regarded as checked exceptions.

## Expected Behavior

* extends [`JObject`](https://github.com/apuliasoft/j2se-js/issues/14) class

* implements [`JSerializable`](https://github.com/apuliasoft/j2se-js/issues/18) interface

* public 0-params constructor `constructor()`
> Constructs a new throwable with null as its detail message.

* public 1-params constructor `constructor(message: JString)`
> Constructs a new throwable with the specified detail message.

* public 2-params constructor `constructor(message: JString, cause: JThrowable)`
> Constructs a new throwable with the specified detail message and cause.

* public 1-params constructor `constructor(cause: JThrowable)`
> Constructs a new throwable with the specified cause and a detail message of (cause==null ? null : cause.toString()) (which typically contains the class and detail message of cause).

* protected 4-params constructor `constructor(message: JString, cause: JThrowable, enableSuppression: Jboolean, writableStackTrace: Jboolean)`
> Constructs a new throwable with the specified detail message, cause, suppression enabled or disabled, and writable stack trace enabled or disabled.

* public method `getCause(): JThrowable`
> Returns the cause of this throwable or null if the cause is nonexistent or unknown.

* public method `getMessage(): JString`
> Returns the detail message string of this throwable.

* public method `toString(): JString`
> Returns a short description of this throwable.

## Do it later
* complete 4-params constructor implementation
* public method `addSuppressed(exception: JThrowable): void`
* public method `fillInStackTrace(): JThrowable`
* public method `getLocalizedMessage(): JString`
* public method `getStackTrace(): Jarray<JStackTraceElement>`
* public method `getSuppressed(): Jarray<JThrowable>`
* public method `initCause(cause: JThrowable): JThrowable`
* public method `printStackTrace(): void`
* public method `printStackTrace(s: JPrintStream): void`
* public method `printStackTrace(s: JPrintWriter): void`
* public method `printStackTrace(stackTrace: Jarray<JStackTraceElement>): void`

**Comment by dammafra** [comment]
In Typescript I can't have an overloaded constructor with different visibility, it has to be the same as others. Protected constructor will be public.

**Comment by dammafra** [comment]
The 4-params constructor has been partially implemented, since its behavior depends on the realization of `JStackTraceElement` class and `JList<E>` interface.
