### ISSUE TITLE
Equality and Relational Operators

### ISSUE THREAD

**Issue by nsanitate** [apuliasoft/j2se-js#9]
Implement the **equality** and **relational operators** that allow to overcome the differences between Java and JavaScript.

## Expected Behavior

* Java `a == b` becomes JavaScript `a.eq(b)`
* Java `a != b` becomes JavaScript `a.ne(b)`
* Java `a < b` becomes JavaScript `a.lt(b)`
* Java `a <= b` becomes JavaScript `a.le(b)`
* Java `a > b` becomes JavaScript `a.gt(b)`
* Java `a >= b` becomes JavaScript `a.ge(b)`

## Acceptance Test
The following program tests the comparison operators:
```typescript
const value1 = new Jint(1);
const value2 = new Jint(2);

if(is(value1.eq(value2)))
   console.log("value1 == value2");

if(is(value1.ne(value2)))
   console.log("value1 != value2");

if(is(value1.gt(value2)))
   console.log("value1 > value2");

if(is(value1.ge(value2)))
   console.log("value1 > value2");

if(is(value1.lt(value2)))
   console.log("value1 < value2");

if(is(value1.le(value2)))
   console.log("value1 <= value2");
```
Output:
```
value1 != value2
value1 <  value2
value1 <= value2
```

**Comment by giuseppe-santoro** [comment]
Why not just `is(a).eq(b)` instead of `J.is(a).eq(b)`?

**Comment by nsanitate** [comment]
Let's change approach: implement the functions in the objects:
• Java `a == b` becomes JavaScript `a.eq(b)`
• Java `a != b` becomes JavaScript `a.ne(b)`
• Java `a < b` becomes JavaScript `a.lt(b)`
• Java `a <= b` becomes JavaScript `a.le(b)`
• Java `a > b` becomes JavaScript `a.gt(b)`
• Java `a >= b` becomes JavaScript `a.ge(b)`

**Comment by giuseppe-santoro** [comment]
I suggest to use an `interface` for each group of operator, in according to https://docs.oracle.com/javase/tutorial/java/nutsandbolts/operators.html

So, we should have:
`jpostfix, junary, jmultiplicative, jadditive, jshift, jrelational, jequality, jbitwise, jbitwise, jbitwise, jlogical, jlogical, jternary, jassignment`
